spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyfeed?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


#  jpa:
#    hibernate:
#      ddl-auto: create
#    #    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  #        format_sql: true
#  #        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "sangwha0@gmail.com" #"sangwha0@gmail.com"
    password:  "clof gkny npng munw" #"doel dvgy bwfh xnfz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      port: 6379
      host: localhost
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

gcp:
  firebase:
    service-account: classpath:firebase/firebase_service_key.json

cloud:
  aws:
    credentials:
      access-key: AKIAZVAIZ2ZCBAQINZDY
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: goribuckettest
    stack:
      auto: false

chatjwt:
  secretKey: v7Xl4QFC9tnEpLxmyEGwNk7N6jX0cgTVUhMXDeH5rvg=
